name: Tests
on: [push, pull_request]
jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python}}
        architecture: x64

    - name: Install Python packages
      run: |
        pip install pytest pytest-mock requests

    - name: Run tests
      run: pytest -v $PWD/test
